language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

services:
  - docker

cache:
  directories:
  - $GOPATH/pkg

before_script:
  - ci/start-okd-4.0.0.sh

after_failure:
  - docker ps -a
  - for log in $(docker ps -qa | xargs); do docker logs --tail 500 $log; done

script:
  - make image
  - make setup
  - make test-e2e-17 KUBECONFIG=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/admin.kubeconfig
  - make test-e2e-18 KUBECONFIG=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/admin.kubeconfig

deploy:
  provider: script
  script: bash build/docker_push.sh
  on:
    branch: master
