apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-operator
  namespace: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wildfly-operator
  template:
    metadata:
      labels:
        name: wildfly-operator
    spec:
      serviceAccountName: wildfly-operator
      containers:
        - name: wildfly-operator
          # Replace this with the built image name
          image: quay.io/jmesnil/wildfly-operator
          command:
          - wildfly-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wildfly-operator"
